services:
  web.api:
    image: web.api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: demodatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

