services:
  webapi:
    container_name: web-api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - "5086:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=projectSetup-postgres-db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - app-network
