services:
  webapi:
    container_name: web-api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: projectSetup-postgres-container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: projectSetup-postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
